services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - app
    restart: always
    container_name: docmind-web-service

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
      - ollama
    container_name: docmind-app

  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: docmind-db

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    container_name: docmind-ollama

volumes:
  pgdata:
  ollama_data: